#! /bin/bash

# Ensure the images are built
pushd workspace-images
./build-images
popd

# Ensure the server is built
pushd backend
./start -r -d docker-env-server
popd

echo "Server is now running as daemon, tailing logs..."
docker logs -f docker-env-server