#! /bin/bash

tag=docker-env-server:local

while getopts ":hrd" opt; do
  case ${opt} in
    d ) args="-d"
	echo "setting daemon mode..."
      ;;
    r) rebuild=1
      ;;
    h) echo "Usage: start [-h] [-r (rebuild)] [-d (daemon)] [container name default=docker-env-server]"
            exit 0
      ;;
  esac
done

if ! docker inspect $tag 2>&1 >/dev/null
then
    rebuild=1
fi

[[ -n "$rebuild" ]] && docker build -t $tag .


container_name=${@:$OPTIND:1}
[[ -z "$container_name" ]] && container_name=docker-env-server

echo "Name: $container_name"

docker run $args --name "$container_name" -p "3001:3001" -v "/var/run/docker.sock:/var/run/docker.sock" -v "$(pwd)/../.cache/:/data" docker-env-server:local

