#! /bin/bash

tag=docker-env-server:local

while getopts ":hrd" opt; do
  case ${opt} in
    d ) args="-d"
	echo "setting daemon mode..."
      ;;
    r) rebuild=1
      ;;
    h) echo "Usage: start [-h] [-r (rebuild)] [-d (daemon)]"
            exit 0
      ;;
  esac
done

if ! docker inspect $tag 2>&1 >/dev/null
then
    rebuild=1
fi

[[ -n "$rebuild" ]] && docker build -t $tag .


docker run $args --name "docker-env" -p "3001:3001" -v "/var/run/docker.sock:/var/run/docker.sock" -v "$(pwd)/../.cache/:/data" docker-env-server:local

