FROM ubuntu:20.04 

SHELL ["/bin/bash", "-c"]

USER root

# Install baseline packages
RUN apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install --yes \
      bash \
      build-essential \
      ca-certificates \
      curl iputils-ping dnsutils \
      docker.io \
      htop \
      locales \
      man \
      python python3 python3-pip python3-cryptography python3-netifaces \
      software-properties-common \
      sudo \
      systemd \
      systemd-sysv \
      unzip \
      jq \
      git jq procps ftp sqlite3 netcat \
      tzdata openssh-server \
      libxtst6 libxrender1 libxi6 libgtk-3-0 libfontconfig1 \
      vim \
      wget && \
    # Install latest Git using their official PPA
    add-apt-repository ppa:git-core/ppa && \
    DEBIAN_FRONTEND="noninteractive" apt-get install --yes git

# Enables Docker starting with systemd
RUN systemctl enable docker

# Add docker-compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

# # Install IntelliJ stuff

# # Run everything as root
USER root

# Install intellij
RUN mkdir -p /opt/idea
RUN curl -L "https://download.jetbrains.com/product?code=IIC&latest&distribution=linux" | tar -C /opt/idea --strip-components 1 -xzvf -

# # Add a binary to the PATH that points to the intellij startup script.
RUN ln -s /opt/idea/bin/idea.sh /usr/bin/intellij-idea-community

# Install projector
RUN pip3 install projector-installer

# Add VSCode-server
RUN curl -fsSL https://code-server.dev/install.sh | sh
COPY start-code-server start-projector /usr/local/bin/
RUN chmod +x /usr/local/bin/start-*
COPY install-projector /usr/local/bin
RUN chmod +x /usr/local/bin/install-projector

RUN echo "/usr/local/bin/start-code-server" >> /etc/profile.d/code-server.sh

COPY ensure_user.sh /root
COPY entrypoint.sh /root

EXPOSE 22

ENV ENV_USER=""

CMD ["/root/entrypoint.sh"]
