version: "3"

services:

    docker:
        image: docker:dind
        restart: unless-stopped
        container_name: "dind-{{.User}}-{{.Name}}"
        # TODO: investigate sysbox to avoid this
        privileged: true
        expose:
            - 2375
            - 2376
        environment:
            - DOCKER_TLS_CERTDIR=
        volumes:
            - "{{.User}}-{{.Name}}-volume:/home/{{.User}}"
            {{if .Params.CopyHostDns}}- "/etc/resolv.conf:/etc/resolv.conf"{{end}}
        {{if .DockerArgs}}command: "{{.DockerArgs}}"{{end}}

    workspace:
        image: {{.Image}}
        restart: unless-stopped
        hostname: "{{.User}}-{{.Name}}"
        container_name: "space-{{.User}}-{{.Name}}"
        ports:
            - "{{.SshPort}}:22"
            - "{{.VsCodePort}}:8080"
            - "{{.ProjectorPort}}:9999"
        environment:
            DOCKER_HOST: "tcp://docker:2375"
            ENV_USER: "{{.User}}"
            ENV_USER_PASSWORD: "{{.Password}}"
            {{ if .PubKey }}PUBKEY: "{{.PubKeyEncoded}}"{{ end }}
        volumes:
            - "{{.User}}-{{.Name}}-volume:/home/{{.User}}"
volumes:
  {{.User}}-{{.Name}}-volume:
